from pathlib import Path

files = [Path('functions/parceiro/[slug].js'), Path('functions/parceiro-feed/[slug].js')]
css = r'''
<style>
/* FINAL LANDING POLISH — premium contact conversion block */
.main{position:relative;isolation:isolate}.main:before{content:'';position:absolute;top:0;left:12%;right:12%;height:1px;background:linear-gradient(90deg,transparent,rgba(200,147,88,.32),transparent);pointer-events:none}
.property-sections{padding-top:14px}.property-section{scroll-margin-top:92px}.category-nav{margin-top:28px;margin-bottom:34px}.category-chip{min-height:82px;transition:transform .2s cubic-bezier(.23,1,.32,1),box-shadow .2s ease}.category-chip:hover{transform:translateY(-3px);box-shadow:0 16px 28px rgba(28,55,59,.1)}
.contact{position:relative;isolation:isolate;display:grid;grid-template-columns:minmax(0,.86fr) minmax(0,1.14fr);gap:42px;align-items:center;margin:92px auto 32px;padding:46px 48px;border:1px solid rgba(229,184,120,.26);overflow:hidden}.contact:before{content:'';position:absolute;inset:auto -10% -55% 35%;height:360px;background:radial-gradient(circle,rgba(229,184,120,.2),transparent 65%);pointer-events:none}.contact>div,.contact>form{position:relative;z-index:1}.contact .eyebrow{color:#e5b878}.contact h2{max-width:440px;font-size:clamp(36px,4vw,56px);line-height:1.02;margin:12px 0 16px}.contact p{max-width:430px;color:rgba(255,255,255,.76);line-height:1.65}.contact-profile{display:flex;align-items:center;gap:12px;margin-bottom:24px}.contact-profile .profile-photo{width:54px;height:54px;border-radius:50%;object-fit:cover;border:2px solid rgba(229,184,120,.88)}.contact-profile strong{display:block;color:#fff;font-family:Fraunces,serif;font-size:20px}.contact-profile small{display:block;color:rgba(255,255,255,.68);font-size:11px;margin-top:4px}.contact .nav-cta{display:inline-flex;margin-top:12px;background:transparent;border:1px solid rgba(255,255,255,.42);border-radius:9px}.contact-form{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:24px;border:1px solid rgba(255,255,255,.2);border-radius:14px;background:rgba(255,255,255,.095);box-shadow:0 18px 42px rgba(0,0,0,.14);backdrop-filter:blur(10px)}.contact-form input,.contact-form textarea{width:100%;min-height:46px;border:1px solid rgba(255,255,255,.24);border-radius:8px;background:rgba(255,255,255,.92);color:#17313a;padding:12px 13px;font:14px 'DM Sans',sans-serif;outline:none;transition:border-color .18s ease,box-shadow .18s ease}.contact-form input:focus,.contact-form textarea:focus{border-color:#e5b878;box-shadow:0 0 0 3px rgba(229,184,120,.2)}.contact-form textarea{grid-column:1/-1;min-height:112px;resize:vertical}.contact-form .consent{grid-column:1/-1;display:flex;gap:8px;align-items:flex-start;color:rgba(255,255,255,.76);font-size:11px;line-height:1.45}.contact-form .consent input{width:auto;min-height:0;margin-top:2px;accent-color:#e5b878}.contact-form .consent a{color:#f0c988}.contact-form .form-submit{grid-column:1/-1;justify-self:start;min-height:46px;padding:0 22px;border:0;border-radius:8px;background:#e5b878;color:#17313a;font-weight:700;cursor:pointer;transition:transform .16s ease,filter .16s ease}.contact-form .form-submit:hover{filter:brightness(1.05);transform:translateY(-2px)}.contact-form .form-submit:active{transform:scale(.97)}.form-message{grid-column:1/-1;color:#e5b878;font-size:12px}.final-intents{margin-top:34px;padding-bottom:10px}.final-intents a{border:1px solid rgba(18,63,74,.1);box-shadow:0 10px 26px rgba(28,55,59,.05);transition:transform .2s ease,box-shadow .2s ease}.final-intents a:hover{transform:translateY(-3px);box-shadow:0 16px 30px rgba(28,55,59,.09)}
@media(max-width:800px){.contact{grid-template-columns:1fr;gap:24px;margin-top:60px;padding:30px 22px}.contact h2{font-size:40px}.contact-form{padding:18px}}
@media(max-width:520px){.contact{margin-left:-2px;margin-right:-2px;padding:26px 17px;border-radius:15px}.contact-form{grid-template-columns:1fr;gap:10px}.contact-form textarea,.contact-form .consent,.contact-form .form-submit,.form-message{grid-column:auto}.contact-form .form-submit{width:100%}.contact h2{font-size:35px}.final-intents{grid-template-columns:1fr!important}}
@media(prefers-reduced-motion:reduce){.category-chip,.final-intents a,.contact-form .form-submit{transition:none}}
</style>
'''
for path in files:
    text = path.read_text()
    if 'FINAL LANDING POLISH' in text:
        continue
    text = text.replace('</head>', css + '</head>', 1)
    path.write_text(text)
    print(path)
